# 6a. Norma inducida

##### Importando librerías

In [1]:
import numpy as np
import random

##### Se crea un algoritmo donde lo primero que hace es crear una matriz de hilbert NxM siendo N=M (Cuadratica), luego se crean varios vectores canonicos de tamaño N y de cantidad M. Se multiplican esos vectores Canonicos con la matriz creada y el resultados son otros vectores. A estos vectores se le saca la norma P y luego se escoge el maximo valor de estas normas generadas. El resultado seria la Norma Inducida de la matriz generada.

In [2]:
   
def hilbert(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1 / (i + j + 1)
    return H

def random_canonical_vectors(n, m):
    # Generate m random canonical vectors of size n
    vectors = []
    for i in range(m):
        e = np.zeros(n)
        e[i % n] = 1
        vectors.append(e)
    return vectors

def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

def max_minkowski_norm(n, m, p):
    # Generate a random matrix of size n by m with integer numbers
    x = hilbert(n)
    # Generate m random canonical vectors of size n
    vectors_canonicos = random_canonical_vectors(n, m)
    # Calculate the product of the matrix and the canonical vectors
    resultado = [np.transpose(x) @ vectors_canonicos[i] for i in range(len(vectors_canonicos))]
    # Calculate the Minkowski norm of each product vector
    normas = [minkowski_norm(v, p) for v in resultado]
    # Find the maximum norm
    maximo = max(normas)
    return maximo



##### Aquí se debe de ingresar el valor de n = # y por ultimo de la norma que se quiere hallar P = "1", "2" y "inf".

In [3]:

n =5
p = 2 
m = n
max_norm = max_minkowski_norm(n, m, p)
print(max_norm)

1.209797962930634


### Si quiere ver el paso a paso detallado de como funciona el algoritmo, en las proximas lineas se muestra explicitamente como funciona.

##### Se generan los números aleatorios para alimentar la función de la matriz

In [15]:
n =  random.randint(2, 11)
m = n

##### Función para crear la matriz de hilbert (cuadrada)

In [16]:

def hilbert(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1 / (i + j + 1)
    return H

x = hilbert(n)

In [17]:
print(x)
x.shape

[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]


(4, 4)

##### Se crean los vectores Canonicos con tamño "n" y el número de vectores es "m"

In [5]:
vectores_canonicos = [] # Lista de vectores canónicos aleatorios

for i in range(m): # Generar m vectores canónicos
    e = np.zeros(n) # Vector canónico de longitud n
    e[i % n] = 1 # Establecer el valor de 1 en la posición correspondiente
    vectores_canonicos.append(e) # Agregar el vector canónico a la lista

for e in vectores_canonicos:
    print(e)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


##### Se hace la multiplicación de la matriz aleatoria y los vectores canonicos 

In [6]:
resultado = [np.transpose(x) @ vectores_canonicos[i] for i in range(len(vectores_canonicos))]
print(resultado)

[array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909]), array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
       0.08333333]), array([0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
       0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333,
       0.07692308]), array([0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
       0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308,
       0.07142857]), array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667]), array([0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.0625    ]), array([0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
  

##### Se crea la función para generar normas vectoriales

In [7]:
def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

##### Aquí se debe de escoger la norma que se desea implementar. (1,2,infinito)

In [8]:
# Normas P 
p = 1 
# p = 2
# P = "inf"

normas =[]
for v in resultado:
    norma = minkowski_norm(v,p)
    normas.append(norma)
    
print(normas)

[3.0198773448773446, 2.1032106782106785, 1.6801337551337547, 1.418228993228993, 1.2348956598956597, 1.09739565989566, 0.9895525226407579, 0.9022509353391707, 0.8298825142865391, 0.768771403175428, 0.7163904507944756]


##### Se saca el maximo de las normas vectoriales 

In [9]:
maximo = max(normas)
print(maximo)

3.0198773448773446
