# 6. Norma inducida

##### Importando librerías

In [12]:
import numpy as np
import random

##### Se crea un algoritmo donde lo primero que hace es crear una matriz NxM, luego se crean varios vectores canonicos de tamaño N y de cantidad M. Se multiplican esos vectores Canonicos con la matriz creada y el resultados son otros vectores. A estos vectores se le saca la norma P y luego se escoge el maximo valor de estas normas generadas. El resultado seria la Norma Inducida de la matriz generada.

In [21]:
def random_matrix(n, m):
    # Generate a random matrix of size n by m with integer numbers
    matrix = np.random.randint(low=0, high=10, size=(n, m))
    return matrix

def random_canonical_vectors(n, m):
    # Generate m random canonical vectors of size n
    vectors = []
    for i in range(m):
        e = np.zeros(n)
        e[i % n] = 1
        vectors.append(e)
    return vectors

def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

def max_minkowski_norm(n, m, p):
    # Generate a random matrix of size n by m with integer numbers
    x = random_matrix(n, m)
    # Generate m random canonical vectors of size n
    vectors_canonicos = random_canonical_vectors(n, m)
    # Calculate the product of the matrix and the canonical vectors
    resultado = [np.transpose(x) @ vectors_canonicos[i] for i in range(len(vectors_canonicos))]
    # Calculate the Minkowski norm of each product vector
    normas = [minkowski_norm(v, p) for v in resultado]
    # Find the maximum norm
    maximo = max(normas)
    return maximo



##### Aquí se debe de ingresar el valor de n = #, luego el valor de m = # y por ultimo de la norma que se quiere hallar P = "1", "2" y "inf". 

In [36]:
n =5
m =10
p = 2 

max_norm = max_minkowski_norm(n, m, p)
print(max_norm)

23.62202362203543


### Si se quiere ver el paso a paso detallado de como funciona el algoritmo, en las proximas lineas se muestra explicitamente como funciona.

##### Función para crear una matriz aleatoria

In [13]:
def random_matrix(n, m):
    # Generate a random matrix of size n by m with integer numbers
    matrix = np.random.randint(low=0, high=10, size=(n, m))
    return matrix

##### Se generan los números aleatorios para alimentar la función de la matriz

In [37]:
n =  random.randint(2, 11)
m = random.randint(2, 11)

x = random_matrix(n,m)
print(x)
x.shape

[[6 0 2 4 2 1 9 1 2 1]
 [2 9 3 6 9 3 3 7 1 5]
 [2 4 7 3 8 8 2 7 5 9]
 [0 4 7 1 4 8 0 1 8 4]
 [7 2 2 1 6 5 6 9 6 5]
 [8 5 9 5 6 2 4 3 8 5]
 [0 2 4 6 0 1 0 4 9 4]
 [9 2 5 0 6 6 9 9 7 5]
 [4 9 1 4 6 0 9 4 8 7]
 [9 6 6 8 7 0 6 2 0 9]
 [3 0 3 4 8 8 5 0 2 6]]


(11, 10)

##### Se crean los vectores Canonicos con tamño "n" y el número de vectores es "m" 

In [38]:
x = random_matrix(n, m)

vectores_canonicos = [] # Lista de vectores canónicos aleatorios

for i in range(m): # Generar m vectores canónicos
    e = np.zeros(n) # Vector canónico de longitud n
    e[i % n] = 1 # Establecer el valor de 1 en la posición correspondiente
    vectores_canonicos.append(e) # Agregar el vector canónico a la lista

for e in vectores_canonicos:
    print(e)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [39]:
vectores_canonicos[0].shape

(11,)

##### Se hace la multiplicación de la matriz aleatoria y los vectores canonicos 

In [40]:
resultado = [np.transpose(x) @ vectores_canonicos[i] for i in range(len(vectores_canonicos))]
print(resultado)

[array([3., 4., 0., 4., 2., 6., 3., 1., 0., 4.]), array([1., 9., 5., 9., 4., 6., 7., 2., 3., 9.]), array([7., 4., 9., 5., 6., 9., 7., 2., 2., 1.]), array([3., 9., 9., 8., 2., 9., 9., 8., 0., 5.]), array([0., 7., 3., 1., 7., 0., 9., 1., 9., 7.]), array([0., 1., 8., 6., 7., 3., 4., 4., 4., 0.]), array([5., 6., 3., 6., 8., 7., 9., 4., 5., 9.]), array([9., 2., 3., 3., 2., 7., 9., 6., 8., 7.]), array([0., 7., 0., 9., 7., 3., 5., 0., 0., 4.]), array([7., 8., 4., 5., 1., 5., 0., 5., 8., 6.])]


##### Se crea la función para generar normas vectoriales

In [41]:
def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

##### Aquí se debe de escoger la norma que se desea implementar. (1,2,infinito)

In [42]:
# Normas P 
p = 1 
# p = 2
# P = "inf"

normas =[]
for v in resultado:
    norma = minkowski_norm(v,p)
    normas.append(norma)
    
print(normas)

[27.0, 55.0, 52.0, 62.0, 44.0, 37.0, 62.0, 56.0, 35.0, 49.0]


##### Se saca el maximo de las normas vectoriales 

In [43]:
maximo = max(normas)
print(maximo)  ## Esta es la norma inducida para la matriz generada

62.0
